# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Arobases\SyliusTransporterLabelGenerationPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Arobases\SyliusTransporterLabelGenerationPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~

acme_sylius_product:
    path: /product/{id}
    defaults:
        _controller: Arobases\SyliusTransporterLabelGenerationPlugin\Controller\GreetingController::getproduct